# Generated by Django 5.2.5 on 2025-08-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('habilitado', models.BooleanField(null=True)),
                ('es_producto', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(blank=True, max_length=45, null=True)),
                ('es_producto', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nit', models.CharField(blank=True, max_length=15, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(null=True)),
                ('es_producto', models.BooleanField(null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Derivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivado', models.CharField(blank=True, max_length=45, null=True)),
                ('factorconversion', models.FloatField(blank=True, null=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.medida')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nombregenerico', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('habilitado', models.BooleanField(null=True)),
                ('maximo', models.IntegerField(blank=True, null=True)),
                ('minimo', models.IntegerField(blank=True, null=True)),
                ('composicion', models.CharField(blank=True, max_length=255, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_producto', models.BooleanField(null=True)),
                ('laboratorio_id', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categoria')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.medida')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('habilitado', models.BooleanField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('costodescuento', models.FloatField(blank=True, null=True)),
                ('fechaingreso', models.DateField(blank=True, null=True)),
                ('terminado', models.FloatField(blank=True, null=True)),
                ('lotetotal', models.FloatField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('productolugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productolugar')),
            ],
        ),
    ]
