# Generated by Django 5.2.5 on 2025-09-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='habilitado',
            field=models.BooleanField(null=True),
        ),
    ]
