# Generated by Django 5.2.5 on 2025-09-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_medida_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
