# Generated by Django 5.2.5 on 2025-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_eliminado_categoria_eliminado_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivado',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='derivado',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
