# Generated by Django 5.2.5 on 2025-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_derivado_eliminado_derivado_eliminado_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
