# Generated by Django 5.2.5 on 2026-03-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_empresa_eliminado_empresa_eliminado_ts_and_more'),
        ('productos', '0006_producto_eliminado_producto_eliminado_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolugar',
            name='lugar',
            field=models.ForeignKey(blank=True, db_column='Lugar_idLugar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productolugar_set', to='lugares.lugar'),
        ),
        migrations.AlterField(
            model_name='productolugar',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productolugar_set', to='productos.producto'),
        ),
    ]
