# Generated by Django 5.2.5 on 2026-03-11 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_add_lugar_to_productolugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_entrada', models.FloatField(blank=True, null=True)),
                ('cant_salida', models.FloatField(blank=True, null=True)),
                ('ultima_existencia', models.FloatField(blank=True, null=True)),
                ('fechahora', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=45, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.FloatField(blank=True, default=0, null=True)),
                ('detalle_compra_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle_factura_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle_salida_id', models.BigIntegerField(blank=True, null=True)),
                ('productolugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientoproducto_set', to='productos.productolugar')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_entrada', models.CharField(blank=True, max_length=45, null=True)),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('anulado', models.BooleanField(blank=True, null=True)),
                ('detalle_factura_id', models.BigIntegerField(blank=True, null=True)),
                ('movimiento_producto_destino', models.ForeignKey(db_column='MovimientoProducto_id_b_', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='productos.movimientoproducto')),
                ('movimiento_producto_origen', models.ForeignKey(db_column='MovimientoProducto_id_a_', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='productos.movimientoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_entrada', models.FloatField(blank=True, null=True)),
                ('cant_salida', models.FloatField(blank=True, null=True)),
                ('ultima_existencia', models.FloatField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientolote_set', to='productos.lote')),
                ('movimiento_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientolote_set', to='productos.movimientoproducto')),
            ],
        ),
    ]
