# Generated by Django 5.2.5 on 2026-03-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_compra_es_farmacia_remove_telefono_doctor_id_and_more'),
        ('productos', '0008_add_movimiento_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoproducto',
            name='detalle_compra_id',
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, db_column='DetalleCompra_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_producto', to='compras.detallecompra'),
        ),
    ]
