# Generated by Django 5.2.5 on 2026-03-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0002_empresa_eliminado_empresa_eliminado_ts_and_more'),
        ('productos', '0008_add_movimiento_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nit', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(blank=True, null=True)),
                ('es_medicamento', models.BooleanField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField()),
                ('total', models.FloatField()),
                ('factura', models.CharField(max_length=8)),
                ('anulada', models.BooleanField(blank=True, default=False, null=True)),
                ('credito', models.BooleanField(blank=True, default=False, null=True)),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=45, null=True)),
                ('es_farmacia', models.BooleanField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('lugar', models.ForeignKey(db_column='Lugar_idLugar', on_delete=django.db.models.deletion.PROTECT, to='lugares.lugar')),
                ('proveedor', models.ForeignKey(db_column='Proveedor_id', on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('precioventa', models.FloatField(blank=True, null=True)),
                ('cant_devuelta', models.FloatField(blank=True, null=True)),
                ('anulada', models.BooleanField(blank=True, null=True)),
                ('compra', models.ForeignKey(db_column='Compra_id', on_delete=django.db.models.deletion.PROTECT, to='compras.compra')),
                ('productolugar', models.ForeignKey(db_column='MedicamentoLugar_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productolugar')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=13)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.BigIntegerField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(blank=True, db_column='Proveedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
                ('tipotel', models.ForeignKey(db_column='TipoTel_id', on_delete=django.db.models.deletion.PROTECT, to='compras.tipotel')),
            ],
        ),
    ]
