# Generated by Django 5.2.5 on 2026-03-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_populate_tipotel_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='es_farmacia',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='eliminado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
