# Generated by Django 5.2.5 on 2026-03-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_compra_es_farmacia_remove_telefono_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='productolugar',
            field=models.ForeignKey(db_column='ProductoLugar_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productolugar'),
        ),
    ]
