# Generated by Django 5.2.5 on 2026-04-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detallecompra_productolugar_db_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefono',
            name='cliente_id',
        ),
    ]
