# Generated by Django 5.2.5 on 2026-04-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_telefono_cliente_id'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='Cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
    ]
