# Generated by Django 5.2.5 on 2026-04-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0005_remove_telefono_cliente_id'),
        ('lugares', '0002_empresa_eliminado_empresa_eliminado_ts_and_more'),
        ('productos', '0009_movimientoproducto_detalle_compra_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('nit', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('activo', models.BooleanField(blank=True, help_text='1 Activo / 0 No Activo', null=True)),
                ('dpi', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='LugarReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LugarReq',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Motivo',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('documentono', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Salida',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(blank=True, null=True)),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=45, null=True)),
                ('anulada', models.BooleanField(blank=True, default=False, null=True)),
                ('entregada', models.BooleanField(blank=True, default=False, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('credito', models.BooleanField(blank=True, null=True)),
                ('nombrefactura', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionfactura', models.CharField(blank=True, max_length=255, null=True)),
                ('nitfactura', models.CharField(blank=True, max_length=15, null=True)),
                ('impresa', models.BooleanField(blank=True, null=True)),
                ('nofactura', models.CharField(blank=True, max_length=45, null=True)),
                ('refacturado', models.BooleanField(blank=True, null=True)),
                ('clientesvarios', models.BooleanField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='Cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
                ('lugar', models.ForeignKey(db_column='Lugar_idLugar', on_delete=django.db.models.deletion.PROTECT, to='lugares.lugar')),
                ('lugarreq', models.ForeignKey(db_column='LugarReq_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.lugarreq')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('cantidad_real', models.FloatField(blank=True, null=True)),
                ('cantidad_entregada', models.FloatField(blank=True, null=True)),
                ('cantidad_entregada_real', models.FloatField(blank=True, null=True)),
                ('cantidad_devuelta', models.FloatField(blank=True, null=True)),
                ('cantidad_devuelta_real', models.FloatField(blank=True, null=True)),
                ('anulado', models.BooleanField(blank=True, null=True)),
                ('devolver', models.BooleanField(blank=True, null=True)),
                ('precionormal', models.FloatField(blank=True, null=True)),
                ('precioventa', models.FloatField(blank=True, null=True)),
                ('derivado', models.ForeignKey(db_column='Derivado_id', on_delete=django.db.models.deletion.PROTECT, to='productos.derivado')),
                ('productolugar', models.ForeignKey(db_column='MedicamentoLugar_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productolugar')),
                ('factura', models.ForeignKey(db_column='Factura_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.factura')),
            ],
            options={
                'db_table': 'DetalleFactura',
            },
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(blank=True, db_column='FechaHora', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('anulado', models.BooleanField(blank=True, db_column='Anulado', default=False, null=True)),
                ('nodocumento', models.CharField(blank=True, db_column='NoDocumento', max_length=45, null=True)),
                ('chequepago', models.CharField(blank=True, db_column='ChequePago', max_length=45, null=True)),
                ('proveedor', models.ForeignKey(db_column='Proveedor_id', on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'db_table': 'PagoCredito',
            },
        ),
        migrations.CreateModel(
            name='DetallePagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(blank=True, db_column='Monto', null=True)),
                ('nofacturapagada', models.CharField(blank=True, db_column='NoFacturaPagada', max_length=100, null=True)),
                ('compra', models.ForeignKey(db_column='Compra_id', on_delete=django.db.models.deletion.PROTECT, to='compras.compra')),
                ('pagocredito', models.ForeignKey(db_column='PagoCredito_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.pagocredito')),
            ],
            options={
                'db_table': 'DetallePagoCredito',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('cantidad_real', models.FloatField(blank=True, null=True)),
                ('anulado', models.BooleanField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('derivado', models.ForeignKey(db_column='Derivado_id', on_delete=django.db.models.deletion.PROTECT, to='productos.derivado')),
                ('productolugar', models.ForeignKey(db_column='MedicamentoLugar_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productolugar')),
                ('salida', models.ForeignKey(db_column='Salida_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.salida')),
            ],
            options={
                'db_table': 'DetalleSalida',
            },
        ),
    ]
