# Generated by Django 5.2.5 on 2025-10-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='LugarTipo',
            fields=[
                ('idLugarTipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Lugar',
                'verbose_name_plural': 'Tipos de Lugar',
                'db_table': 'LugarTipo',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('idLugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('num_placa', models.CharField(blank=True, max_length=8, null=True)),
                ('empresa', models.ForeignKey(db_column='Empresa_idEmpresa', on_delete=django.db.models.deletion.PROTECT, related_name='lugares', to='lugares.empresa')),
                ('lugar_tipo', models.ForeignKey(db_column='LugarTipo_idLugarTipo', on_delete=django.db.models.deletion.PROTECT, related_name='lugares', to='lugares.lugartipo')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'Lugar',
                'indexes': [models.Index(fields=['lugar_tipo'], name='Lugar_LugarTi_e2dec1_idx'), models.Index(fields=['empresa'], name='Lugar_Empresa_3e504f_idx')],
            },
        ),
    ]
