# Generated by Django 5.2.5 on 2025-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugartipo',
            name='eliminado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lugartipo',
            name='eliminado_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
